### intro to OOP in python

In [2]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

test() for the class and method


In [4]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
print(p1.fact(5))#120

120


In [9]:
class demo2:
    def _init_(self,p1,p2):
        self.p1=p1
        self.p2=p2
       
    def add(self,p1,p2):
        return p1+p2
    
c1=demo2(10,20)
print(c1.add(100,200))

TypeError: demo2() takes no arguments

In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [3]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [13]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[4.8338599  6.56109838 3.71129766 5.69483873 4.10904559 3.99851885
 4.92222629 4.41275919 3.32166765 5.12698173]
min value= 3.321667651358241
max value= 6.561098383835137
mean value= 4.669229396714558
median value= 4.623309542515105


In [14]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [17]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [18]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [21]:
import pandas as pd
dict{"name":["anil","akhil","dinesh","harsha","ajay","kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"mobile number":[999,888,777,888,777,999],"address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

SyntaxError: invalid syntax (<ipython-input-21-9b811b4d169a>, line 2)